source 'git@github.com:talk-to/private-cocoapod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'ForgeTests' do
  pod 'Forge', :path => '../'
  target 'ForgeTestsTests' do
    inherit! :search_paths
  end
end
